[theme]
base = "light"
primaryColor = "#0a1614"
backgroundColor = "#E8FDF9"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1a2e2a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
